version: '3'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NAME_NODE_URL=http://172.20.0.6:5000
    networks:
      mynet:
        ipv4_address: 172.20.0.7

networks:
  mynet:
    external:
      name: mynet