version: "3"
services:
  datanode1:
    container_name: datanode1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NAME_NODE_IP=34.233.186.39:5000
      - DATANODE_INTERNAL_IP=172.20.0.2:3000
      - DATANODE_EXTERNAL_IP=44.221.239.169:3000
    networks:
      mynet:
        ipv4_address: 172.20.0.2

  datanode2:
    container_name: datanode2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NAME_NODE_IP=34.233.186.39:5000
      - DATANODE_INTERNAL_IP=172.20.0.3:3001
      - DATANODE_EXTERNAL_IP=44.221.239.169:3001
    networks:
      mynet:
        ipv4_address: 172.20.0.3
  datanode3:
    container_name: datanode3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NAME_NODE_IP=34.233.186.39:5000
      - DATANODE_INTERNAL_IP=172.20.0.4:3002
      - DATANODE_EXTERNAL_IP=44.221.239.169:3002
    networks:
      mynet:
        ipv4_address: 172.20.0.4
  datanode4:
    container_name: datanode4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NAME_NODE_IP=34.233.186.39:5000
      - DATANODE_INTERNAL_IP=172.20.0.5:3003
      - DATANODE_EXTERNAL_IP=44.221.239.169:3003
    networks:
      mynet:
        ipv4_address: 172.20.0.5
networks:
  mynet:
    external:
      name: mynet
