version: '3'
services:
  namenode:
    container_name: namenode
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NAME_NODE_PORT=5000
    networks:
      mynet:
        ipv4_address: 172.20.0.6
networks:
  mynet:
    external:
      name: mynet